declare module '*.css';
declare module '*.less';
declare module '*.scss';
declare module '*.sass';
declare module '*.svg';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.png';
declare module '*.gif';
